service: smite-sage-backend
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 4096
  timeout: 30
  # usagePlan: # limit monthly invocations
  #   quota:
  #     limit: 1000000
  #     offset: 2
  #     period: MONTH
  #   throttle:
  #     burstLimit: 200
  #     rateLimit: 100

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  # - serverless-plugin-chrome

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 4000
